FIX: End if-then block and simplify code (#8)
The if-then block did not have a proper ending. This commit also
simplifies the code a bit because the else-branch (exit 0) did not do
anything.

```
yarn run v1.22.5
$ /home/runner/work/discourse-plugin/discourse-plugin/node_modules/.bin/prettier -v
2.1.2
Done in 0.24s.
/home/runner/work/_temp/7c858813-e0e9-45b7-9b7f-3e87943c87e4.sh: line 8: syntax error: unexpected end of file
Error: Process completed with exit code 2.
```